### ISSUE TITLE
pgdiff does not work with PostgreSQL 8

### ISSUE THREAD

**Issue by gward** [joncrlsn/pgdiff#1]
I'm trying to run pgdiff against two servers running PG 8.4. Unfortunately, pgdiff seems to make lots of assumptions that do not hold with PG 8. Example:
```
$ bin-linux64/pgdiff [...] table
[...]
2015/01/15 16:19:36 Error running querypq: syntax error at or near "COLLATE"
```
or:
```
$ bin-linux64/pgdiff [...] index
[...]
2015/01/15 16:20:49 Error running querypq: column con.conindid does not exist
```
or:
```
$ bin-linux64/pgdiff [...] role
[...]
2015/01/15 16:21:30 Error running querypq: column r.rolreplication does not exist
```

Etc, etc. Looks like nothing works.

It would be awesome if pgdiff worked with PG 8 as well as 9. But if it only works with 9, please at least say so in the README! Then I can just skip it and look for another tool.

**Comment by joncrlsn** [comment]
Hi Gward, I'm embarrassed to admit that I didn't see your post until more than a year later.  I'm adding a filter to my gmail so I see these right away.

Since it's not likely I'll get this working with Postgres 8, I'll update the README.  I'm sorry you had to find out the hard way.
