### ISSUE TITLE
Did your program really work?

### ISSUE THREAD

**Issue by cabezon666** [joncrlsn/pgdiff#11]
Hi,

I have a doubt.  I tried to use your program with all the parameters, but it always shows "Not yet handled: \"
Could you put a practical example of how to use it.  And thanks again!

**Comment by joncrlsn** [comment]
Thanks for the feedback.  Can you send an example of what you tried? (switch URLs and such for privacy) That might help me figure out what you are hitting and how it can be handled better.

**Comment by cabezon666** [comment]
Just solve it!
The problem is it reads '\' as the function to do.  Maybe you should try to change the example on the webpage because could be troublesome to understand it.

Example:
**pgdiff -U dbuser -H localhost -D refDB  -O "sslmode=disable" \
       -u dbuser -h localhost -d compDB -o "sslmode=disable" \
       TABLE** 

What I did:
**pgdiff TABLE -U dbuser -H localhost -D refDB  -O "sslmode=disable" \
       -u dbuser -h localhost -d compDB -o "sslmode=disable"**

'TABLE' change the position. Maybe for a person with experience could be nothing, but for a newbie like me took a little of time to figure out.

Thank you again for this program! really usefull and also thanks for your quick reply.
