### ISSUE TITLE
pgdiff won't see any changes in TABLE

### ISSUE THREAD

**Issue by camyb81** [joncrlsn/pgdiff#12]
Hi,

Let me start by saying that I enjoy this project and like the initiative you've taken to create this tool #like

I've been playing around with the tool and I'm running into some walls and hopefully somebody can give me some feedback on the issue below.

Whenever I run the script against 2 databases (Postgres 9.5) it never finds any diffs on the TABLE option. On the other hand it does find diffs on eg. constraints of tables which are present in Database A but not in Database B, but a missing column or missing table isn't hit...

Commando:
./pgdiff -U postgres -W password -H localhost -P 5432 -D test1 -O 'sslmode=disable' -u postgres -w password -h localhost -p 5432 -d test2 -o 'sslmode=disable' TABLE

Output (always the same, even if there are tables present in one database and not in the other):
-- schemaType: TABLE
-- db1: {test1 localhost 5432 postgres password sslmode=disable}
-- db2: {test2 localhost 5432 postgres password sslmode=disable}
-- Run the following SQL against db2:

Is this a known bug that COLUMN and TABLE options are not doing anything? 
Am I doing something wrong?

Greets.

**Comment by joncrlsn** [comment]
Thanks for the feedback.  That doesn't sound right, unless the metadata queries for COLUMN and TABLE do not work in Postgres 9.5.

You could try manually running the SQL found near the bottom of these files on both databases:
https://github.com/joncrlsn/pgdiff/blob/master/column.go
https://github.com/joncrlsn/pgdiff/blob/master/table.go

If that SQL errors, or does not return any data then some internals have probably changed in 9.5 and I'll have to fix the query to work.

Here are the queries to speed things along for you:
SELECT table_name
    , CASE table_type WHEN 'BASE TABLE' THEN 'TABLE' ELSE table_type END AS table_type
    , is_insertable_into
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_type = 'BASE TABLE'
ORDER BY table_name;

SELECT table_name
    , column_name
    , data_type
    , is_nullable
    , column_default
    , character_maximum_length
FROM information_schema.columns 
WHERE table_schema = 'public'
AND is_updatable = 'YES'
ORDER BY table_name, column_name;

If they do return data then there is probably another issue with the queries that I haven't run into yet.

**Comment by camyb81** [comment]
Hey Jon,

Nice to hear from you so soon.
I've just run both queries on the database and indeed both return null
See attachments.

I hope to hear from you and even maybe looking forward for a fix :)
Thanks, Bryan

Jon Carlson schreef op 2017-01-10 20:41:

**Comment by camyb81** [comment]
Hi Jon,

I was a bit too quick on executing the queries on my test databases 
(Postgres 9.5). After looking into your queries, I've created some 
tables on the public schema and the queries do return results.

Please see the attachments.

Greets,
Bryan

Jon Carlson schreef op 2017-01-10 20:41:

**Comment by camyb81** [comment]
Hi Jon, 

An update from my side...
I've created some modifications to the table.go and column.go so all schemas are compared and also the output syntax is generated including the schema. 

Example (new output):
ALTER TABLE ABC.XYZ ADD CONSTRAINT CCC FOREIGN KEY (id_aaa)
REFERENCES ABC.ZZZ (id_bbb) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;

Is it possible to update the project?
Can I send you the sources?

**TABLE:**
SELECT table_name
, CASE table_type WHEN 'BASE TABLE' THEN 'TABLE' ELSE table_type END AS table_type
, is_insertable_into
, table_schema
FROM information_schema.tables
WHERE table_schema not like '%pg_%'
AND table_type = 'BASE TABLE'
ORDER BY table_name;

**COLUMN (sql variable example):**
SELECT table_name
    , column_name
    , data_type
    , is_nullable
    , column_default
    , character_maximum_length
    , table_schema
FROM information_schema.columns
WHERE table_schema not like '%pg_%'
AND is_updatable = 'YES'
ORDER BY table_name, column_name;

Also some updates on the printf statements.

**Comment by joncrlsn** [comment]
Nice.  Thank you for your suggestion.  

So you have a custom schema that is not "public".  I should have considered that.  I'll need to fix all the queries.

Can you make a pull request with your suggested changes?  Or send me a patch file?

Thanks again,

- Jon

**Comment by camyb81** [comment]
Where do you want me to send it? I can send you a copy of my current status.

**Comment by joncrlsn** [comment]
camyb,  I've created the 0.9.2 branch.  If you feel like forking the 0.9.2 branch and making your changes there and recreating your pull request against that, it'd be great. Otherwise,  I think I know what you are aiming at and have started making the changes.  How much of a hurry are you in?

**Comment by joncrlsn** [comment]
Also, you asked where you can send your changes.  You can attach files to a comment.

**Comment by camyb81** [comment]
Jon, 
I'm not in a hurry, but if you have an update available then I'll be happy to give it a try and test it on my environment. Did you see my upload of some modded .go files?

**Comment by joncrlsn** [comment]
I saw a pull request, but it was against the wrong branch.  Thanks for the offer to test it out.  I've been making some commits against the 0.9.2 branch if you want to check them out.  

It's been taking me longer because I need to set up a test database that I can include in the source code.  I don't want to send you a totally broken test.  

Do you have a go environment you could build the 0.9.2 branch, or will you want a pre-built binary?

**Comment by joncrlsn** [comment]
Hi Camyb, I had time to work on it tonight and so I made some fixes, did some manual testing, and generated new binaries.  You won't find them on the main page, however they are in the branch listed below.  Let me know how this goes for you.  You can google chat me at joncrlsn if that helps.

https://github.com/joncrlsn/pgdiff/tree/release/0.9.3

**Comment by jmguazzo** [comment]
Hi, I tested your tool regarding this issue and it works for me. 
I added a column in a table in a schema that's not "public" and it was found.
Could it be possible to specify the schema as an option either with the -0 or as a new "-S" parameter ?

**Comment by joncrlsn** [comment]
> Could it be possible to specify the schema as an option either with the -0 or as a new "-S" parameter ?

I think that's a good idea.  People should be able to choose the schema they diff against.

**Comment by hitigon** [comment]
@joncrlsn yes, I have a use case to compare two different schemas

**Comment by joncrlsn** [comment]
@hitigon thanks for the reminder and the knowledge that it's value to people.  I'll work on that this week.

**Comment by joncrlsn** [comment]
I apologize for not getting to this earlier.  I've started digging into it tonight and I should be able to work on it more this weekend.

**Comment by joncrlsn** [comment]
@jmguazzo and @hitigon   The 1.0b1 pre-release allows you to specify the schema names you want to compare.  It took more work than I expected (to get it right), but I enjoyed it regardless.  Download the latest and let me know if you have any comments.  Thanks!

- Jon

**Comment by joncrlsn** [comment]
I'm closing this issue.  The schema issues *should* be fixed in version 1.0 which can be downloaded as a pre-release now.
