### ISSUE TITLE
Suggestion: remove binaries from git repo

### ISSUE THREAD

**Issue by LrsK** [joncrlsn/pgdiff#17]
This project seems nice, but you really should get rid of the binaries from the git repository. It makes it cumbersome and wasteful to work with the repo.

Use releases instead: https://help.github.com/articles/distributing-large-binaries/
(I see you have already used the release feature in Github)

**Comment by joncrlsn** [comment]
Very good point.  I agree, git is not good for larger binaries.  So I'll see about improving this.

**Comment by joncrlsn** [comment]
Thank you, LrsK, for your helpful comment.  I used BFG to clean the binaries out of the repository and will be adding binaries to each release from now on.
