### ISSUE TITLE
Error running querypq: SSL is not enabled on the server

### ISSUE THREAD

**Issue by klammbueddel** [joncrlsn/pgdiff#2]
Hi, when trying to execute pgdiff I get the message as stated in the title. What am I missing. How to enable SSL on the server?

I am not sure which part requires SSL. To establish a connection to a postgres server should not require SSL IMHO, maybe you can proof me wrong?

**Comment by joncrlsn** [comment]
I mistakenly didn't document the -o1 and -o2 arguments.  You'll want to use them:

-o1 "sslmode=disable" -o2 "sslmode=disable"

I apologize for how long it took me to realize people had submitted issues to this project.

**Comment by dragomirr** [comment]
I know this is closed subject but I'm still getting this error. Here is my query:
`pgdiff -D widb -U widbuser -H 127.0.0.1 -O "sslmode=disable" -P 5433 -d widb -u widbuser -h 127.0.0.1 -o "sslmode=disable" -p 5434 INDEX` and here is output:
-- schemaType: INDEX
-- db1: {widb 127.0.0.1 5433 widbuser  sslmode=disable}
-- db2: {widb 127.0.0.1 5434 widbuser  sslmode=disable}
-- Run the following SQL against db2:
2016/06/10 08:40:45 Error running querypq: SSL is not enabled on the server

I've tries on different machines (ubuntu 16.04 and centos 7) and got same results. Also I have tried FUNCTION and TABLE options.

I even tried -o1 and -o2 options, but then I'm getting Not yet handled: SSLMODE=DISABLE  

If you have any idea why is this happening please share it. Thanks in advance.

**Comment by kensongoo** [comment]
@dragomirr I had the same issue. The problem for me was I didn't specify  the password. Use -W for the first db password and -w for the second db password. The error message was misleading.

**Comment by joncrlsn** [comment]
Thanks for your suggestion, Ken.

**Comment by dragomirr** [comment]
Thanks Ken.
