### ISSUE TITLE
fatal error: systemstack called from unexpected goroutine

### ISSUE THREAD

**Issue by JMurphyWeb** [joncrlsn/pgdiff#23]
### System versions:

OSX Version: 10.13.2 (High Sierra)
```
$ psql --version
psql (PostgreSQL) 9.5.10
```

## Command

Whilst running the following command:
`$ ~/Downloads/pgdiff/pgdiff  -U jmurphy -D engine_dev  -O "sslmode=disable" -S public \
       -u jmurphy -h localhost -d ev2_dev -o "sslmode=disable" -s public \
       TABLE`

I get the following errors:

## Error

```
...

fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine
fatal error: systemstack called from unexpected goroutine

[1]    63624 bus error  ~/Downloads/pgdiff/pgdiff -U jmurphy -D engine_dev -O "sslmode=disable" -S  -
```

I want to compare two local database schema's, from two databases called `ev2_dev` (newer) and `engine_dev` (older), both of which user jmurphy has read/write access to.

Any idea why I'm getting this error?

**Comment by joncrlsn** [comment]
Are you using the provided download or did you compile from source?  I merged a pull request recently that might have caused a problem on the master branch.

**Comment by JMurphyWeb** [comment]
I think it was provided download. I'll close this now though because I found an alternative solution. 
Thanks for your response!

**Comment by kamalkech** [comment]
@JMurphyWeb : can you tell me what is an alternative solution ??

**Comment by JMurphyWeb** [comment]
@kamalkech this service worked for me: https://www.apgdiff.com/download.php

**Comment by amitabhkant** [comment]
apgdiff will not work PG10
