### ISSUE TITLE
Column comparison

### ISSUE THREAD

**Issue by SparkeyG** [joncrlsn/pgdiff#6]
There is a case where a varchar in db1 has no maxlength, but in db2 it has a length of 1024 and nothing will be reported. If you run the comparison the other way pgdiff suggests altering the length of the columns to 1024 with no warning of data loss.

**Comment by joncrlsn** [comment]
Hi SparkeyG, I'm sorry I didn't see your post until more than 6 months later.  I've added a filter to my gmail so I see these emails right away.

I will add a data loss warning in the next version.

**Comment by joncrlsn** [comment]
The warning is on the 0.9.1 branch
